### ISSUE TITLE
Figma Cleanup

### ISSUE THREAD

**Issue by ellenvanwyk** [nasa-jpl/stellar#38]
- [ ] [Turn table hover into variable](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=6896:21783#277063744)
- [ ] [Use success green as variable](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=6830:24836#276341624)
- [ ] [Add warning yellow?](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=6830:24836#276339546)
- [ ] [Documentation on when to use which type styles](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=1:4439#154314613)
- [ ] [Standardize label vs body use](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=5981:14044#154311238)
- [ ] [Add "filled" to input](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=4834:0#139479626)
- [ ] @lklyne [check color variable opacity](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=6830:24751#290278089)
- [ ] [Add pagination to tables](https://www.figma.com/file/a696svN2S7YNlZRYAkeLob?node-id=5750:9312#290197616)
